media:
  input: public/uploads
  output: /uploads
components:
  category:
    type: object
    label: Category
    fields:
      - name: title
        type: string
      - name: description
        type: text
content:
  - name: announcements
    label: Announcements
    type: collection
    path: content/announcements
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Content
        type: rich-text
        required: true
      - name: speaker
        label: Speaker
        type: string
      - name: place
        label: Place
        type: string
      - name: category
        label: Category
        type: string
      - name: image
        label: Image
        type: image
      - name: date
        label: Date
        type: date
      - name: description
        label: Description
        type: text