media:
  input: public/uploads
  output: /uploads
content:
  - name: announcements
    label: Announcements
    type: collection
    path: content/announcements
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Content
        type: rich-text
        required: true
      - name: speaker
        label: Speaker
        type: string
      - name: place
        label: Place
        type: string
      - name: category
        label: Category
        type: string
      - name: image
        label: Image
        type: image
      - name: date
        label: Date
        type: date
      - name: description
        label: Description
        type: text
  - name: information
    label: Informations
    type: collection
    path: content/informations
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Content
        type: rich-text
        required: true
      - name: place
        label: Place
        type: string
      - name: category
        label: Category
        type: string
      - name: gallery
        label: Gallery
        type: image
        options:
          multiple:
            max: 6
          unique: true
          extensions: [jpg, png]
          rename: true
      - name: date
        label: Date
        type: date